name: islamic
description: "Islamic Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.2.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.11
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: ElMessiri
      fonts:
        - asset: assets/fonts/ElMessiri-SemiBold.ttf

